name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4']
    name: PHP ${{ matrix.php-versions }}
    env:
      AWS_ACCESS_KEY_ID: foo
      AWS_SECRET_ACCESS_KEY: bar
      AWS_CSM_ENABLED: false
    steps:
    - name: Setup PHP with Xdebug
      uses: shivammathur/setup-php@v2
      with:
        coverage: xdebug
        php-version: ${{ matrix.php-versions }}
        ini-values: xdebug.overload_var_dump=0, memory_limit=4G


    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - if: ${{ matrix.php-versions == '7.1' }}
      name: customize for phpunit 5
      run: composer require --dev --ignore-platform-reqs phpunit/phpunit "^5.7.11"

    - if: ${{ matrix.php-versions == '5.5' }}
      name: customize for phpunit 5
      run: composer require --dev --ignore-platform-reqs phpunit/phpunit "4.8.36"

    - if: ${{ matrix.php-versions == '5.5' }}
      name: remove xdebug config
      run: sudo rm /etc/php5/cli/conf.d/20-xdebug.ini

    - if: ${{ matrix.php-versions == '5.6' }}
      name: customize for phpunit 5
      run: composer --version

    - if: ${{ matrix.php-versions == '7.0' }}
      name: customize for phpunit 5
      run: composer --version

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer update --no-interaction --prefer-source

    - name: Run test suite
      run: make test
